// <auto-generated />
using System;
using GreenMarket.Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GreenMarket.Application.Migrations
{
    [DbContext(typeof(GreenMarketDbContext))]
    partial class GreenMarketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("greenmarket")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GreenMarket.Domain.Entities.Categorie", b =>
                {
                    b.Property<int>("CategorieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("categorie_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategorieId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("libelle");

                    b.HasKey("CategorieId");

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.ToTable("categorie", "greenmarket");
                });

            modelBuilder.Entity("GreenMarket.Domain.Entities.Commande", b =>
                {
                    b.Property<int>("CommandeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("commande_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommandeId"));

                    b.Property<DateTimeOffset>("DateCommande")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_commande");

                    b.Property<decimal>("MontantTotal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("montant_total");

                    b.Property<string>("StatutPaiement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("statut_paiement");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid")
                        .HasColumnName("utilisateur_id");

                    b.HasKey("CommandeId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("commande", "greenmarket", t =>
                        {
                            t.HasCheckConstraint("CK_commande_montant_total", "montant_total >= 0");

                            t.HasCheckConstraint("CK_commande_statut_paiement", "statut_paiement IN ('en_attente', 'paye', 'refuse', 'rembourse', 'annule')");
                        });
                });

            modelBuilder.Entity("GreenMarket.Domain.Entities.LigneCommande", b =>
                {
                    b.Property<int>("CommandeId")
                        .HasColumnType("integer")
                        .HasColumnName("commande_id");

                    b.Property<int>("ProduitId")
                        .HasColumnType("integer")
                        .HasColumnName("produit_id");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("prix_unitaire");

                    b.Property<int>("ProducteurId")
                        .HasColumnType("integer")
                        .HasColumnName("producteur_id");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer")
                        .HasColumnName("quantite");

                    b.HasKey("CommandeId", "ProduitId");

                    b.HasIndex("ProducteurId");

                    b.HasIndex("ProduitId");

                    b.ToTable("ligne_commande", "greenmarket", t =>
                        {
                            t.HasCheckConstraint("CK_ligne_commande_prix_unitaire", "prix_unitaire >= 0");

                            t.HasCheckConstraint("CK_ligne_commande_quantite", "quantite > 0");
                        });
                });

            modelBuilder.Entity("GreenMarket.Domain.Entities.Producteur", b =>
                {
                    b.Property<int>("ProducteurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("producteur_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProducteurId"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("adresse");

                    b.Property<DateTimeOffset>("DateAdhesion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_adhesion");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("NomProducteur")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nom_producteur");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid")
                        .HasColumnName("utilisateur_id");

                    b.HasKey("ProducteurId");

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.ToTable("producteur", "greenmarket");
                });

            modelBuilder.Entity("GreenMarket.Domain.Entities.Produit", b =>
                {
                    b.Property<int>("ProduitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("produit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProduitId"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("integer")
                        .HasColumnName("categorie_id");

                    b.Property<DateTimeOffset>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_creation");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean")
                        .HasColumnName("est_actif");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nom");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("prix_unitaire");

                    b.Property<int>("ProducteurId")
                        .HasColumnType("integer")
                        .HasColumnName("producteur_id");

                    b.Property<int?>("ScoreEnvironnemental")
                        .HasColumnType("integer")
                        .HasColumnName("score_environnemental");

                    b.Property<string>("Tracabilite")
                        .HasColumnType("text")
                        .HasColumnName("tracabilite");

                    b.HasKey("ProduitId");

                    b.HasIndex("CategorieId");

                    b.HasIndex("ProducteurId");

                    b.ToTable("produit", "greenmarket", t =>
                        {
                            t.HasCheckConstraint("CK_produit_prix_unitaire", "prix_unitaire >= 0");

                            t.HasCheckConstraint("CK_produit_score_environnemental", "score_environnemental BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("GreenMarket.Domain.Entities.Stock", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("stock_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StockId"));

                    b.Property<int>("ProduitId")
                        .HasColumnType("integer")
                        .HasColumnName("produit_id");

                    b.Property<int>("QuantiteDisponible")
                        .HasColumnType("integer")
                        .HasColumnName("quantite_disponible");

                    b.Property<int>("SeuilAlerte")
                        .HasColumnType("integer")
                        .HasColumnName("seuil_alerte");

                    b.HasKey("StockId");

                    b.HasIndex("ProduitId")
                        .IsUnique();

                    b.ToTable("stock", "greenmarket", t =>
                        {
                            t.HasCheckConstraint("CK_stock_quantite_disponible", "quantite_disponible >= 0");

                            t.HasCheckConstraint("CK_stock_seuil_alerte", "seuil_alerte >= 0");
                        });
                });

            modelBuilder.Entity("GreenMarket.Domain.Entities.Utilisateur", b =>
                {
                    b.Property<Guid>("KeycloakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("keycloak_id");

                    b.Property<DateTimeOffset>("DateInscription")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_inscription");

                    b.HasKey("KeycloakId");

                    b.ToTable("utilisateur", "greenmarket");
                });

            modelBuilder.Entity("GreenMarket.Domain.Entities.Commande", b =>
                {
                    b.HasOne("GreenMarket.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany("Commandes")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GreenMarket.Domain.Entities.LigneCommande", b =>
                {
                    b.HasOne("GreenMarket.Domain.Entities.Commande", "Commande")
                        .WithMany("LignesCommande")
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenMarket.Domain.Entities.Producteur", "Producteur")
                        .WithMany("LignesCommande")
                        .HasForeignKey("ProducteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenMarket.Domain.Entities.Produit", "Produit")
                        .WithMany("LignesCommande")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Producteur");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("GreenMarket.Domain.Entities.Producteur", b =>
                {
                    b.HasOne("GreenMarket.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithOne("Producteur")
                        .HasForeignKey("GreenMarket.Domain.Entities.Producteur", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GreenMarket.Domain.Entities.Produit", b =>
                {
                    b.HasOne("GreenMarket.Domain.Entities.Categorie", "Categorie")
                        .WithMany("Produits")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenMarket.Domain.Entities.Producteur", "Producteur")
                        .WithMany("Produits")
                        .HasForeignKey("ProducteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Producteur");
                });

            modelBuilder.Entity("GreenMarket.Domain.Entities.Stock", b =>
                {
                    b.HasOne("GreenMarket.Domain.Entities.Produit", "Produit")
                        .WithOne("Stock")
                        .HasForeignKey("GreenMarket.Domain.Entities.Stock", "ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("GreenMarket.Domain.Entities.Categorie", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("GreenMarket.Domain.Entities.Commande", b =>
                {
                    b.Navigation("LignesCommande");
                });

            modelBuilder.Entity("GreenMarket.Domain.Entities.Producteur", b =>
                {
                    b.Navigation("LignesCommande");

                    b.Navigation("Produits");
                });

            modelBuilder.Entity("GreenMarket.Domain.Entities.Produit", b =>
                {
                    b.Navigation("LignesCommande");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("GreenMarket.Domain.Entities.Utilisateur", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("Producteur");
                });
#pragma warning restore 612, 618
        }
    }
}
